import { useState } from 'react';
import { Link, Navigate, useLocation, useNavigate, useSearchParams } from 'react-router-dom';
import { useAuth } from '../contexts/AuthContext';

const avatars = ['🌟', '🦊', '🐼', '🐯', '🦋'];
export default function AuthPage() {
  const { user, login, register } = useAuth();
  const [searchParams, setSearchParams] = useSearchParams();
  const registerMode = searchParams.get('mode') === 'register';
  const [form, setForm] = useState({ name: '', email: '', password: '', avatar: '🌟' });
  const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const navigate = useNavigate(); const location = useLocation();
  const redirect = location.state?.from || '/dashboard';
  if (user) return <Navigate to={redirect} replace />;
  const switchMode = (isRegister) => { setError(''); setSearchParams(isRegister ? { mode: 'register' } : {}); };
  const update = (field, value) => setForm((current) => ({ ...current, [field]: value }));
  const submit = async (event) => { event.preventDefault(); setBusy(true); setError(''); try { const currentUser = registerMode ? await register(form) : await login({ email: form.email, password: form.password }); navigate(currentUser.role === 'admin' ? '/admin' : redirect, { replace: true }); } catch (err) { setError(err.message); } finally { setBusy(false); } };
  const useDemo = () => { setForm((current) => ({ ...current, email: 'aarav@example.com', password: 'Learn@123' })); switchMode(false); };
  return <main className="auth-page"><div className="auth-art"><Link to="/" className="brand"><span className="brand-mark">S</span><span>Safe<span>Buddy</span></span></Link><div className="auth-art__copy"><span className="eyebrow">LEARN · GROW · SPEAK UP</span><h1>Every child deserves to know their rights.</h1><p>Build confidence with thoughtful, age-appropriate learning.</p></div><div className="auth-art__shapes"><i className="shape shape--one"/><i className="shape shape--two"/><i className="shape shape--three"/><span>✦</span><span>☀</span></div></div><section className="auth-panel"><div className="auth-panel__inner"><Link className="back-link" to="/">← Back to home</Link><span className="eyebrow">WELCOME TO SAFEBUDDY</span><h2>{registerMode ? 'Create your learner space' : 'Welcome back!'}</h2><p className="muted">{registerMode ? 'Choose an avatar and start your rights-learning journey.' : 'Continue building your super-safe skills today.'}</p><div className="auth-tabs"><button className={!registerMode ? 'active' : ''} onClick={() => switchMode(false)}>Sign in</button><button className={registerMode ? 'active' : ''} onClick={() => switchMode(true)}>Create account</button></div><form onSubmit={submit} className="auth-form">{registerMode && <><label>Your name<input value={form.name} onChange={(e) => update('name', e.target.value)} placeholder="e.g. Ananya" required maxLength="60" /></label><fieldset><legend>Pick your buddy</legend><div className="avatar-picker">{avatars.map((avatar) => <button type="button" aria-label={`Choose ${avatar}`} className={form.avatar === avatar ? 'selected' : ''} key={avatar} onClick={() => update('avatar', avatar)}>{avatar}</button>)}</div></fieldset></>}<label>Email address<input type="email" value={form.email} onChange={(e) => update('email', e.target.value)} placeholder="you@example.com" required /></label><label>Password<input type="password" value={form.password} onChange={(e) => update('password', e.target.value)} placeholder={registerMode ? 'At least 8 characters' : 'Your password'} required minLength="8" /></label>{error && <p className="form-error">⚠ {error}</p>}<button className="button button--full" disabled={busy}>{busy ? 'One moment…' : registerMode ? 'Create my account →' : 'Sign in →'}</button></form>{!registerMode && <div className="demo-login"><span>Want a quick look?</span><button onClick={useDemo}>Use learner demo account</button><small>Demo: aarav@example.com · Learn@123</small></div>}<p className="auth-privacy">🔒 We only use account details to save your learning progress.</p></div></section></main>;
}
