import { useEffect, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { api } from '../utils/api';
import { useAuth } from '../contexts/AuthContext';
import { SafetyAudio, YouTubeEmbeds } from '../components/SafetyMedia';
import { lessonMedia } from '../utils/safetyMedia';

export default function LessonPage() {
  const { id } = useParams(); const { token } = useAuth(); const [lesson, setLesson] = useState(null); const [completed, setCompleted] = useState(false); const [open, setOpen] = useState(0); const [error, setError] = useState('');
  useEffect(() => { Promise.all([api(`/lessons/${id}`, { token }), api('/progress/me', { token })]).then(([lessonData, progress]) => { setLesson(lessonData.lesson); setCompleted(progress.user.completedLessonIds.includes(id)); }).catch((err) => setError(err.message)); }, [id, token]);
  if (error) return <section className="error-card"><h2>That lesson is unavailable.</h2><p>{error}</p><Link to="/learn" className="button">Back to lessons</Link></section>;
  if (!lesson) return <main className="loading-page"><span className="spinner" /> Opening your lesson…</main>;
  return <article className="lesson-page"><Link to="/learn" className="back-link">← All lessons</Link><header className="lesson-hero" style={{ '--lesson-color': lesson.color }}><div><span className="pill">{lesson.category} · {lesson.level}</span><h1>{lesson.title}</h1><p>{lesson.summary}</p><div className="lesson-hero__meta"><span>◷ {lesson.minutes} min read</span><span>{completed ? '✓ Lesson completed' : '◈ Read, reflect & quiz'}</span></div></div><span className="lesson-hero__icon">{lesson.icon}</span></header><section className="lesson-intro"><span>👋</span><p>Take your time with each idea. You can come back whenever you want.</p></section><SafetyAudio clips={lessonMedia[id]?.clips || []} /><div className="lesson-sections">{lesson.sections.map((section, index) => <article className={`lesson-section ${open === index ? 'open' : ''}`} key={`${index}-${section.heading}`}><button onClick={() => setOpen(open === index ? -1 : index)}><span className="section-count">0{index + 1}</span><span><b>{section.heading}</b><small>{open === index ? 'Tap to close' : 'Tap to explore'}</small></span><i>{open === index ? '−' : '+'}</i></button>{open === index && <div className="lesson-section__content"><p>{section.body}</p>{section.tip && <aside><span>💡</span><div><b>SafeBuddy tip</b><p>{section.tip}</p></div></aside>}</div>}</article>)}</div><YouTubeEmbeds videos={lessonMedia[id]?.videos || []} heading="Videos for this lesson" /><section className="lesson-quiz-cta"><div><span>🧠</span><div><h2>Ready to try a quick check?</h2><p>There are a few friendly questions to help you remember what you learned.</p></div></div><Link className="button" to={`/quiz/${id}`}>{completed ? 'Try quiz again' : 'Start the quiz'} <span>→</span></Link></section><aside className="lesson-disclaimer">SafeBuddy is for learning and reflection. For advice about a real situation, talk to a trusted adult or a qualified support service.</aside></article>;
}

