import { useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { api } from '../utils/api';
import { useAuth } from '../contexts/AuthContext';
import ProgressRing from '../components/ProgressRing';

export default function ProfilePage() {
  const { token, user } = useAuth(); const [data, setData] = useState(null); const [lessons, setLessons] = useState([]);
  useEffect(() => { Promise.all([api('/progress/me', { token }), api('/lessons', { token })]).then(([progress, lessonData]) => { setData(progress); setLessons(lessonData.lessons); }); }, [token]);
  const recent = useMemo(() => data?.attempts?.slice(0, 4) || [], [data]);
  if (!data) return <main className="loading-page"><span className="spinner" /> Opening your journey…</main>;
  const complete = data.stats.totalLessons ? Math.round(data.stats.completedLessons / data.stats.totalLessons * 100) : 0;
  return <><section className="profile-hero"><span className="profile-avatar-large">{user.avatar}</span><div><span className="eyebrow">MY LEARNING JOURNEY</span><h1>{user.name}</h1><p>SafeBuddy learner · Growing with curiosity and courage</p></div><div className="profile-xp"><span>⚡</span><b>{data.user.xp}</b><small>Total XP</small></div></section><section className="profile-stats"><article><span>🔥</span><b>{data.user.streak}</b><small>Day streak</small></article><article><span>◈</span><b>{data.stats.completedLessons}</b><small>Lessons done</small></article><article><span>◉</span><b>{data.stats.averageScore}%</b><small>Quiz average</small></article><article><span>✦</span><b>{data.user.badges.length}</b><small>Badges</small></article></section><section className="profile-grid"><article className="profile-card journey-overview"><div className="section-title"><div><span className="eyebrow">YOUR PATH</span><h2>Progress so far</h2></div></div><div className="journey-overview__body"><ProgressRing value={complete} size={130} stroke={11} /><div><b>{data.stats.completedLessons} of {data.stats.totalLessons} lessons explored</b><p>You’re building knowledge one kind, careful step at a time.</p><p>🎮 {data.stats.gamesCompleted || 0} of {data.stats.totalGames || 0} safety games played</p><Link to="/learn">Explore lessons →</Link> · <Link to="/games">Play games →</Link></div></div></article><article className="profile-card"><span className="eyebrow">YOUR COLLECTION</span><h2>Badges</h2>{data.user.badges.length ? <div className="badge-grid">{data.user.badges.map((badge) => <div key={badge.key} className="badge"><span>{badge.icon}</span><small>{badge.title}</small></div>)}</div> : <p className="muted">Complete a lesson quiz to earn your first badge.</p>}</article></section><section className="section-block"><div className="section-title"><div><span className="eyebrow">RECENT ACTIVITY</span><h2>Your quiz moments</h2></div></div>{recent.length ? <div className="activity-list">{recent.map((attempt) => { const lesson = lessons.find((item) => item.id === attempt.lessonId); return <article key={attempt.id}><span className={attempt.score >= 60 ? 'activity-icon good' : 'activity-icon'}>{attempt.score >= 60 ? '✓' : '↻'}</span><div><b>{lesson?.title || 'Lesson quiz'}</b><small>{new Date(attempt.createdAt).toLocaleDateString(undefined, { month: 'short', day: 'numeric' })} · {attempt.score}% score</small></div><span className="activity-score">{attempt.score >= 60 ? 'Completed' : 'Try again'}</span></article>; })}</div> : <div className="empty-inline"><span>🧠</span><p>Try your first quiz after a lesson — your progress will appear here.</p></div>}</section></>;
}
