import { useEffect, useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { api } from '../utils/api';
import { useAuth } from '../contexts/AuthContext';

export default function QuizPage() {
  const { lessonId } = useParams(); const navigate = useNavigate(); const { token, setUser } = useAuth(); const [quiz, setQuiz] = useState(null); const [answers, setAnswers] = useState([]); const [step, setStep] = useState(0); const [result, setResult] = useState(null); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  useEffect(() => { api(`/quizzes/lesson/${lessonId}`, { token }).then(({ quiz: loadedQuiz }) => { setQuiz(loadedQuiz); setAnswers(Array(loadedQuiz.questions.length).fill(null)); }).catch((err) => setError(err.message)); }, [lessonId, token]);
  const choose = (choice) => setAnswers((current) => current.map((answer, index) => index === step ? choice : answer));
  const submit = async () => { setBusy(true); setError(''); try { const data = await api(`/quizzes/${quiz.id}/submit`, { method: 'POST', body: { answers }, token }); setResult(data); setUser(data.user); } catch (err) { setError(err.message); } finally { setBusy(false); } };
  if (error && !quiz) return <section className="error-card"><h2>Quiz unavailable</h2><p>{error}</p><Link to={`/learn/${lessonId}`} className="button">Back to lesson</Link></section>;
  if (!quiz) return <main className="loading-page"><span className="spinner" /> Loading your quiz…</main>;
  if (result) return <main className="quiz-result"><div className="result-confetti">✦ ✧ ★ ✦</div><span className="result-emoji">{result.passed ? '🎉' : '🌱'}</span><span className="eyebrow">QUIZ COMPLETE</span><h1>{result.passed ? 'Great thinking!' : 'Keep learning — you’ve got this!'}</h1><p>{result.passed ? `You answered ${result.correct} of ${result.total} questions correctly.` : `You answered ${result.correct} of ${result.total}. Review the lesson and try again anytime.`}</p><div className="score-orbit"><b>{result.score}%</b><span>score</span></div><div className="reward-row"><span>⚡ +{result.xpEarned} XP</span>{result.passed && <span>✓ Lesson progress saved</span>}</div><div className="feedback-list">{result.feedback.map((feedback, index) => <article key={index} className={feedback.correct ? 'correct' : 'review'}><span>{feedback.correct ? '✓' : '↗'}</span><div><b>Question {index + 1}: {feedback.correct ? 'Correct!' : 'Review this one'}</b><p>{feedback.explanation}</p></div></article>)}</div><div className="result-actions"><Link className="button" to="/learn">Keep exploring <span>→</span></Link><button className="secondary-button" onClick={() => navigate(`/learn/${lessonId}`)}>Review lesson</button></div></main>;
  const question = quiz.questions[step]; const canContinue = answers[step] !== null;
  return <main className="quiz-page"><Link to={`/learn/${lessonId}`} className="back-link">← Leave quiz</Link><header><span className="eyebrow">QUICK CHECK</span><div className="quiz-title-row"><h1>{quiz.title}</h1><span>⚡ {quiz.xpReward} XP</span></div><div className="quiz-progress"><i style={{ width: `${((step + 1) / quiz.questions.length) * 100}%` }} /></div><p>Question {step + 1} of {quiz.questions.length}</p></header><section className="question-card"><span className="question-number">0{step + 1}</span><h2>{question.prompt}</h2><div className="answer-list">{question.options.map((option, index) => <button key={option} className={answers[step] === index ? 'selected' : ''} onClick={() => choose(index)}><span>{String.fromCharCode(65 + index)}</span>{option}<i>{answers[step] === index ? '✓' : ''}</i></button>)}</div></section>{error && <p className="form-error">⚠ {error}</p>}<footer className="quiz-controls"><button className="secondary-button" onClick={() => setStep((current) => current - 1)} disabled={step === 0}>← Back</button>{step < quiz.questions.length - 1 ? <button className="button" disabled={!canContinue} onClick={() => setStep((current) => current + 1)}>Next question →</button> : <button className="button" disabled={!canContinue || busy} onClick={submit}>{busy ? 'Checking…' : 'See my result →'}</button>}</footer></main>;
}
